source ~/.config/hypr/apps/zsh/starship
source ~/.config/hypr/apps/zsh/syntax/init
source ~/.config/hypr/apps/zsh/completions/init
source ~/.config/hypr/apps/zsh/suggestions
source ~/.config/hypr/apps/zsh/zoxide

autoload -U compinit; compinit

bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey  "^[[3~"  delete-char

HISTFILE=~/.zsh-history
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

alias ls='ls --color=auto -F'
alias grep='grep --color=auto'
alias fastfetch='fastfetch --config ~/.config/hypr/apps/fastfetch.jsonc -l arch_small'
alias bat='bat --force-colorization --theme base16-256'
alias eza='eza -F --icons=always --all -x'

alias ls='eza'
alias l='ls -l'
alias cd='z'
alias cat='bat'
alias _cat='/bin/cat'
alias ..='cd ..'
alias fzf='fzf --preview "bat --force-colorization --theme base16-256"'
alias vencord-installer='sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"'
alias searchfs='sudo find / -name '

unsetopt PROMPT_SP
